apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAzureServiceAllowedPorts
metadata:
  name: service-allowed-ports
spec:
  match:
    excludedNamespaces: {{ .Values.excludedNamespaces }}
    kinds:
      - apiGroups: [""]
        kinds: ["Service"]
  parameters:
    allowedPorts: {{ .Values.allowedServicePorts }}