apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAzureLoadBalancerNoPublicIPs
metadata:
  name: load-balancer-no-public-ips
spec:
  match:
    excludedNamespaces: {{ .Values.excludedNamespaces }}
    kinds:
      - apiGroups: [""]
        kinds: ["Service"]